### ISSUE TITLE
Got object reference null issue when resolve the js file 

### ISSUE THREAD

**Issue by chucklu** [microsoft/ajaxmin#22]
We have added a ScriptBundle of js file, and got exception
```c#
  bundles.Add(new ScriptBundle("~/admin/js").Include("js file path");
```

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Ajax.Utilities.Member.GetFunctionGuess(AstNode target)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.GuessAtName(AstNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(BinaryOperator node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.CallNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.JSParser.InternalParse()
>    at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
>    at System.Web.Optimization.JsMinify.Process(BundleContext context, BundleResponse response)
>    at System.Web.Optimization.Bundle.ApplyTransforms(BundleContext context, String bundleContent, IEnumerable`1 bundleFiles)
>    at System.Web.Optimization.Bundle.GetBundleResponse(BundleContext context)
>    at System.Web.Optimization.BundleResolver.GetBundleContents(String virtualPath)
>    at System.Web.Optimization.AssetManager.EliminateDuplicatesAndResolveUrls(IEnumerable`1 refs)
>    at System.Web.Optimization.AssetManager.RenderExplicit(String tagFormat, String[] paths)
>    at ASP._Page_Views_Shared__AdminLayout_cshtml.Execute() in 
> _AdminLayout.cshtml:line 29
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
>    at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
>    at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
>    at System.Web.WebPages.WebPageBase.<>c__DisplayClass40_0.<RenderPageCore>b__0(TextWriter writer)
>    at System.Web.WebPages.WebPageBase.Write(HelperResult result)
>    at System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body)
>    at System.Web.WebPages.WebPageBase.PopContext()
>    at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
>    at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState)
>    at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult)
>    at System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult)
>    at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
>    at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
>    at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

   
   The file was downloaded from https://datatables.net/download/index
   
[datatables.min.js.zip](https://github.com/microsoft/ajaxmin/files/13237676/datatables.min.js.zip)

**Comment by chucklu** [comment]
The above issue comes from WebGrease
 Microsoft.Ajax.Utilities 
  public class Minifier
packages\WebGrease.1.6.0\lib\WebGrease.dll


We're using [Microsoft.AspNet.Web.Optimization](https://www.nuget.org/packages/Microsoft.AspNet.Web.Optimization#dependencies-body-tab)，and it depends on [WebGrease](https://www.nuget.org/packages/WebGrease/) library.

source code https://webgrease.codeplex.com/
alternative tools https://github.com/dotnet/aspnetcore/issues/1604   
Use [NUglify](https://github.com/xoofx/NUglify) or [JSMin.NET](https://github.com/Taritsyn/JSMin.NET).

**Comment by chucklu** [comment]
This issue happened in Process method of JsMinify class of System.Web.Optimization library.
```c#
	Minifier minifier = new Minifier();
				string content = minifier.MinifyJavaScript(response.Content, new CodeSettings
				{
					EvalTreatment = EvalTreatment.MakeImmediateSafe,
					PreserveImportantComments = false
				});
```
Minifier class located in WebGrease.dll, and error happened in MinifyJavaScript method of Minifier class


> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Ajax.Utilities.Member.GetFunctionGuess(AstNode target)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.GuessAtName(AstNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(BinaryOperator node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(IfNode node)
>    at Microsoft.Ajax.Utilities.IfNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(FunctionObject node)
>    at Microsoft.Ajax.Utilities.FunctionObject.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.TreeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(CallNode node)
>    at Microsoft.Ajax.Utilities.CallNode.Accept(IVisitor visitor)
>    at Microsoft.Ajax.Utilities.AnalyzeNodeVisitor.Visit(Block node)
>    at Microsoft.Ajax.Utilities.JSParser.InternalParse()
>    at Microsoft.Ajax.Utilities.Minifier.MinifyJavaScript(String source, CodeSettings codeSettings)
>    at System.Web.Optimization.JsMinify.Process(BundleContext context, BundleResponse response)


similar issue https://github.com/trullock/NUglify/issues/36
